services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: resultchecker
    ports:
      - "8000:8000"
    volumes:
      - .:/resultchecker
      - ./storage/logs:/resultchecker/storage/logs
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

